### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by rrrrrrmb** [Coder-Srinivas/Ipl-Auction#6]
Hey ,
First of all thanks for creating this awsome project :) . I really enjoyed trying this out. I plan on modifying some parts and would like to add my own set of players to host an auction. So could you please license your project since that defines what other people could do with your code. If at all you need suggestions for licensing you can check [here](https://www.fsf.org/licensing/education)

**Comment by Coder-Srinivas** [comment]
Hey, thanks for pointing it out, I will add a license soon.

**Comment by Coder-Srinivas** [comment]
Added license
