### ISSUE TITLE
Steps to Make the project running needed

### ISSUE THREAD

**Issue by VinaySavla** [Coder-Srinivas/Ipl-Auction#7]
Can you please mention the steps to make the project running and also the versions of node and npm.

**Comment by Coder-Srinivas** [comment]
The dependency issue is now fixed, you can run it by executing the command `npm i` on the server side and client side. Make sure that the mongoDB server is running on localhost:27017. Do reach out to me if you run into any issues.

**Comment by VinaySavla** [comment]
Thank you
